server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/api}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:selab}?useSSL=false&serverTimezone=Asia/Taipei&characterEncoding=utf8&useUnicode=true&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        "[format_sql]": true
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

app:
  jwt:
    secret: ${APP_JWT_SECRET:?APP_JWT_SECRET is required and must be >= 64 bytes}
    exp-minutes: ${APP_JWT_EXP_MINUTES:120}

logging:
  level:
    root: INFO
    "[org.hibernate.SQL]": OFF   # ✅ 用中括號避免 map key 警告
