name: Build and Push Images to GHCR
on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
permissions:
  packages: write
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: backend
            context: ./backend
            dockerfile: ./backend/Dockerfile
            image: ghcr.io/kevin6191015/new_app-backend
          - name: frontend
            context: ./frontend
            dockerfile: ./frontend/Dockerfile.prod
            image: ghcr.io/kevin6191015/new_app-frontend
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}:latest
